"use client";

import React, { useEffect, useState } from 'react';
import { Navbar } from '@/components/Navbar';
import { Hero } from '@/components/Hero';
import { FilterSidebar } from '@/components/FilterSidebar';
import { CollegeCard } from '@/components/CollegeCard';
import { useSearchStore } from '@/store/useSearchStore';

export default function Home() {
  const [started, setStarted] = useState(false);
  const { fetchOptions, search, results, loading, sort_by, setFilter, options } = useSearchStore();

  useEffect(() => {
    fetchOptions();
  }, [fetchOptions]);

  const handleStart = () => {
    setStarted(true);
    // Don't auto-search — let the user configure filters first, then hit Apply
  };

  const exportCSV = () => {
    if (results.length === 0) return;

    const watermark = [
      `"Generated by: Zainul Aabdeen"`,
      `"Source: The College Times — MHT CET College Finder"`,
      `"Exported on: ${new Date().toLocaleString()}"`,
      `""`,
    ].join("\n");

    const headers = [
      "College Code", "College Name",
      "Branch Code", "Branch Name",
      "Region", "Distance (km)",
      "Highest Pkg (LPA)", "Avg Pkg (LPA)", "Median Pkg (LPA)",
      "Placement %", "Top Recruiters",
      "CAP Round", "Category", "Seat Scope",
      "Cutoff Rank", "Cutoff Percentile %", "Rec. Score"
    ].join(",");

    // Flatten: one row per cutoff entry (each cap round / category / scope)
    const rows: string[] = [];
    results.forEach(r => {
      r.cutoffs.forEach(cutoff => {
        rows.push([
          `"${r.college_code}"`,
          `"${r.college_name}"`,
          `"${r.branch_code}"`,
          `"${r.branch_name}"`,
          `"${r.region || ''}"`,
          r.distance_km ?? '',
          r.highest_package_lpa ?? '',
          r.average_package_lpa ?? '',
          r.median_package_lpa ?? '',
          r.placement_percentage ?? '',
          `"${r.top_recruiters || ''}"`,
          `"${cutoff.cap_round}"`,
          `"${cutoff.category}"`,
          `"${cutoff.seat_scope}"`,
          cutoff.cutoff_rank,
          cutoff.cutoff_percentile.toFixed(4),
          cutoff.recommendation_score?.toFixed(2) ?? ''
        ].join(","));
      });
    });

    const csvContent = "data:text/csv;charset=utf-8," + watermark + [headers, ...rows].join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `college_results_by_zainul_${new Date().toISOString().slice(0,10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Navbar />

      {!started ? (
        <Hero onStart={handleStart} />
      ) : (
        <div className="flex-1 max-w-screen-xl mx-auto w-full flex flex-col md:flex-row border-x border-foreground">
          <div className="w-full md:w-80 border-b md:border-b-0 md:border-r border-foreground flex-shrink-0 overflow-y-auto">
            <FilterSidebar />
          </div>

          {/* Main Content */}
          <div className="flex-1 flex flex-col">
            <div className="p-6 border-b border-foreground flex justify-between items-center bg-background z-10 sticky top-[60px]">
              <div className="font-mono text-xs uppercase tracking-widest flex items-center gap-4">
                <span>Showing <span className="font-bold">{results.length}</span> Results</span>
                {results.length > 0 && (
                  <button 
                    onClick={exportCSV}
                    className="border border-[#111111] px-2 py-1 hover:bg-[#111111] hover:text-[#F9F9F7] transition-colors"
                  >
                    Export CSV
                  </button>
                )}
              </div>
              <div className="flex items-center gap-2">
                <label className="text-xs font-mono uppercase">Sort by</label>
                <select 
                  value={sort_by}
                  onChange={e => {
                    setFilter('sort_by', e.target.value);
                    setTimeout(() => search(), 0);
                  }}
                  className="border-b-2 border-foreground bg-transparent px-2 py-1 font-mono text-xs uppercase focus-visible:bg-neutral-100 focus-visible:outline-none sharp-corners cursor-pointer"
                >
                  <option value="">Default</option>
                  <option value="Recommendation Score">Recommendation Score</option>
                  <option value="Highest Cutoff">Highest Cutoff</option>
                  <option value="Lowest Cutoff">Lowest Cutoff</option>
                  <option value="Closest">Closest</option>
                  <option value="Highest Package">Highest Package</option>
                  <option value="Highest Placement %">Highest Placement %</option>
                </select>
              </div>
            </div>

            <div className="flex-1 bg-neutral-100 p-6 sm:p-8 newsprint-texture">
              {loading ? (
                <div className="w-full h-64 flex items-center justify-center">
                  <p className="font-mono uppercase tracking-widest animate-pulse">Loading data...</p>
                </div>
              ) : results.length > 0 ? (
                <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 relative z-10">
                  {results.map((college, idx) => (
                    <CollegeCard key={`${college.college_code}-${college.branch_code}-${idx}`} college={college} />
                  ))}
                </div>
              ) : (
                <div className="w-full h-64 flex flex-col items-center justify-center border-2 border-dashed border-foreground p-8 text-center bg-background relative z-10">
                  <p className="font-serif text-2xl font-bold mb-2">
                    {results.length === 0 && !loading ? 'Set your filters and click Apply' : 'No Results Found'}
                  </p>
                  <p className="font-mono text-sm text-muted-foreground uppercase tracking-widest">
                    {results.length === 0 && !loading ? 'Use the sidebar to customise your search' : 'Try adjusting your filters'}
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Print-only watermark — visible only when printing / saving as PDF */}
      <div
        id="print-watermark"
        style={{
          display: 'none',
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          zIndex: 9999,
          pointerEvents: 'none',
          alignItems: 'center',
          justifyContent: 'center',
        }}
        className="print-watermark-overlay"
      >
        <div style={{
          fontSize: '72px',
          fontWeight: 900,
          color: 'rgba(17,17,17,0.06)',
          transform: 'rotate(-35deg)',
          textTransform: 'uppercase',
          letterSpacing: '-2px',
          userSelect: 'none',
          fontFamily: 'serif',
          whiteSpace: 'nowrap',
        }}>
          Zainul Aabdeen
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t-4 border-foreground bg-background py-8 px-4 mt-auto">
        <div className="max-w-screen-xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="font-serif font-black text-2xl tracking-tighter">THE COLLEGE TIMES</div>
          <div className="font-mono text-xs uppercase tracking-widest text-muted-foreground text-center">
            Edition: Vol 1.0 | Data from CAP AY 2025–2026 | Not an official recommendation
          </div>
          <div className="font-mono text-xs text-muted-foreground italic">
            Made by <span className="font-bold not-italic text-foreground">Zainul Aabdeen</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
